ClubTrophies: 189
userlist:
- 587262745
- 5398258926
- 965991778
- 944737635
- 1351862795
- 1692914062
- 885241590
- 1776839854
- 1723223576
- 1627845759
- 1120841593
- 1199804150
- 2116328571
- 658551070
- 1193654237
- 784193884
- 1790362763
- 5202556843
- 1349357882
- 5133646963
- 1230083523
- 5282701558
- 922572148
- 2032965601
- 5670080583
- 489061592
user:
  587262745:
    Tag: PG28CU9QR
    Nickname: üî™MESSERNüî™
    Team: 9
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230129T160148.000Z
  5398258926:
    Tag: 2JVROG2QJ
    Nickname: –ª–µ–æ–Ω
    Team: 3
    TimeZoneDifference: 2
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T172552.000Z
  965991778:
    Tag: CR89LJQC
    Nickname:  ≥·µòÀ¢ƒê√∏‚Ç≤‚Ç≤…è‚ô°
    Team: 6
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T085624.000Z
  944737635:
    Tag: 89RV0LUGO
    Nickname: .thaise‚ô°‚úåüèø|BS
    Team: 4
    TimeZoneDifference: 0
    DailyTrophies: 9
    WeeklyTrophies: 9
    TotalTrophies: 9
    LastCheckedGame: 20230201T181742.000Z
  1351862795:
    Tag: VV8UY09R
    Nickname: ‚õàÔ∏èƒê‚Ç≥‚±§‚Ç≠ ‚Ç≤‚±ß√ò‚Ç¥‚ÇÆü•Ä
    Team: 6
    TimeZoneDifference: 2
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T111740.000Z
  1692914062:
    Tag: PQQ28YRYC
    Nickname: snyusoed
    Team: 9
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T102023.000Z
  885241590:
    Tag: 9JYYULPYG
    Nickname: –í–∞–¥–∏–º –ö—É—Ä—Å–µ–¥–æ–≤
    Team: 6
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T142609.000Z
  1776839854:
    Tag: 8UYGUUJVG
    Nickname: ‚ñ™Ô∏è‚ôß@[$niper]‚ôß‚ñ™Ô∏è
    Team: 4
    TimeZoneDifference: 0
    DailyTrophies: 9
    WeeklyTrophies: 9
    TotalTrophies: 9
    LastCheckedGame: 20230201T181742.000Z
  1723223576:
    Tag: 28PRV8UVY
    Nickname: _]LP[mr –º–∞–∫—Å06_
    Team: 4
    TimeZoneDifference: 0
    DailyTrophies: 9
    WeeklyTrophies: 9
    TotalTrophies: 9
    LastCheckedGame: 20230201T181742.000Z
  1627845759:
    Tag: 8092892L2
    Nickname: _Prosto_Angel_
    Team: 5
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T165305.000Z
  1120841593:
    Tag: V9VQVLC
    Nickname: SMK|SoBoring
    Team: 1
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T165815.000Z
  1199804150:
    Tag: P0Q88UL90
    Nickname: ‚ô°Ô∏é·¥õ·¥è·¥ç  ú·¥Ä Ä·¥Ö è‚Ä¢
    Team: 5
    TimeZoneDifference: 2
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T165305.000Z
  2116328571:
    Tag: 8LYYRRR0
    Nickname: GCG|Trej—ÖüèØ
    Team: 5
    TimeZoneDifference: 1
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T165305.000Z
  658551070:
    Tag: J9LRJU28
    Nickname: Bad Boy
    Team: 2
    DailyTrophies: 0
    WeeklyTrophies: 0
    TimeZoneDifference: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T174941.000Z
  784193884:
    Tag: 29R9PYUC8
    Nickname: ‚ò¢Ô∏è–°–ú–≠–†–¢–¨‚ò¢Ô∏è
    Team: 2
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T132259.000Z
  1193654237:
    Tag: QQGPVJRP
    Nickname: „Ñí‰πáÁà™Ôæå‰∏®“ú
    Team: 3
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T172552.000Z
  1790362763:
    Tag: YYLLRV280
    Nickname: –º–∞—Ä–∞—Ç
    Team: 2
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T113941.000Z
  5202556843:
    Tag: 9PJUR2QQP
    Nickname: DO–®IK|YT
    Team: 3
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T172552.000Z
  1349357882:
    Tag: Y998R89UV
    Nickname: MrGloss15
    Team: 7
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T181016.000Z
  922572148:
    Tag: 9J0L0RRQG
    Nickname: TilaysüÉèüåÜ
    Team: 7
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T180850.000Z
  5133646963:
    Tag: 8J8JUQ8GC
    Nickname: –†–æ–∫–¥–æ–∫
    Team: 8
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230131T185113.000Z
  1230083523:
    Tag: 880VJ9QR9
    Nickname: Íú∞·¥á ü·¥Ö èüé∫
    Team: 8
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T172319.000Z
  5282701558:
    Tag: Q0R0UQUJ
    Nickname: –ß–ò–¢–ï–†777
    Team: 8
    TimeZoneDifference: -1
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230201T174614.000Z
  2032965601:
    Tag: 20PYYL2PP
    Nickname: SMK | spoilEel
    Team: 1
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T165815.000Z
  5670080583:
    Tag: P09Y098P0
    Nickname: SMK|mopik gopik
    Team: 1
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230201T165815.000Z
  489061592:
    Tag: 2Q20VQP2
    Nickname: y—ë—ëtCC
    Team: 0
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: Netu
