ClubTrophies: 96
userlist:
- 1193654237
- 5398258926
- 5202556843
- 885241590
- 965991778
- 1351862795
- 587262745
- 1692914062
user:
  1193654237:
    Tag: QQGPVJRP
    Nickname: „Ñí‰πáÁà™Ôæå‰∏®“ú
    Team: 1
    TimeZoneDifference: 0
    DailyTrophies: 14
    WeeklyTrophies: 14
    TotalTrophies: 14
    LastCheckedGame: 20230203T172446.000Z
  5398258926:
    Tag: 2JVROG2QJ
    Nickname: –ª–µ–æ–Ω
    Team: 1
    TimeZoneDifference: 2
    DailyTrophies: 14
    WeeklyTrophies: 14
    TotalTrophies: 14
    LastCheckedGame: 20230203T172446.000Z
  5202556843:
    Tag: 9PJUR2QQP
    Nickname: DO–®IK|YT
    Team: 1
    TimeZoneDifference: 0
    DailyTrophies: 14
    WeeklyTrophies: 14
    TotalTrophies: 14
    LastCheckedGame: 20230203T172446.000Z
  885241590:
    Tag: 9JYYULPYG
    Nickname: –í–∞–¥–∏–º –ö—É—Ä—Å–µ–¥–æ–≤
    Team: 2
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230203T185508.000Z
  965991778:
    Tag: CR89LJQC
    Nickname:  ≥·µòÀ¢ƒê√∏‚Ç≤‚Ç≤…è‚ô°
    Team: 2
    TimeZoneDifference: 0
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230203T185508.000Z
  1351862795:
    Tag: VV8UY09R
    Nickname: ‚õàÔ∏èƒê‚Ç≥‚±§‚Ç≠ ‚Ç≤‚±ß√ò‚Ç¥‚ÇÆü•Ä
    Team: 2
    TimeZoneDifference: 2
    DailyTrophies: 18
    WeeklyTrophies: 18
    TotalTrophies: 18
    LastCheckedGame: 20230203T185508.000Z
  587262745:
    Tag: PG28CU9QR
    Nickname: üî™MESSERNüî™
    Team: 3
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230203T173808.000Z
  1692914062:
    Tag: PQQ28YRYC
    Nickname: snyusoed
    Team: 3
    TimeZoneDifference: 0
    DailyTrophies: 0
    WeeklyTrophies: 0
    TotalTrophies: 0
    LastCheckedGame: 20230203T124626.000Z
